import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar/navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ paddingTop: "180px" }}>{children}</div> {/* Adjust based on navbar height */}
      </body>
    </html>
  );
}

