# Generated by Django 5.1.1 on 2025-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=20)),
                ('player_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('player_game_stats', models.JSONField()),
            ],
        ),
    ]
